### ISSUE TITLE
Gray external link

### ISSUE THREAD

**Issue by ksheedlo** [rackerlabs/canon#154]
I want a class that I can use for gray external links. Here is an example:

![screen shot 2015-06-22 at 2 50 00 pm](https://cloud.githubusercontent.com/assets/1271410/8294005/ff71074a-18ed-11e5-864a-397b695e43f2.png)

This is a change in development to monitoring.rackspace.net, which broke during the last Canon release since the sprite offsets shifted and I'm hard coding the offset in a custom stylesheet. I'd like to prevent that from happening again.

**Comment by bradgignac** [comment]
@ksheedlo we'd be honored if you would add yourself to the (nonexistent) contributor's section of our NPM package. See https://docs.npmjs.com/files/package.json#people-fields-author-contributors for more info. Thanks!

**Comment by eddywashere** [comment]
:+1:

**Comment by bradgignac** [comment]
@eddywashere You, too.
